name: Java with Gradle and Test Report

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Run tests
      run: ./gradlew test

    - name: Generate test report
      run: ./gradlew generateTestReport

    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: build/reports/tests

  generate-report:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download test report
      uses: actions/download-artifact@v2
      with:
        name: test-report
        path: build/reports/tests

    - name: Generate HTML report
      run: |
        mkdir -p reports
        cp -r build/reports/tests reports/
