name: Java with Gradle and Test Report

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Download chromedriver
      run: |
        mkdir -p drivers
        curl -SL https://chromedriver.storage.googleapis.com/{version}/chromedriver_linux64.zip -o chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d drivers
        chmod +x drivers/chromedriver

    - name: Run tests with chromedriver
      run: |
        export PATH=$PATH:$PWD/drivers
        ./gradlew test

    - name: Generate test report
      run: ./gradlew generateTestReport

    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: test-output/HtmlReport/

  generate-report:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download test report
      uses: actions/download-artifact@v2
      with:
        name: test-report
        path: build/reports/tests

    - name: Generate HTML report
      run: |
        mkdir -p build/reports/tests
        cp -r test-output/HtmlReport/ build/reports/tests
